micronaut:
  application:
    name: keyManager

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/key_manager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 87499813
    dialect: POSTGREES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true


erp-itau:
  pix:
    url: 'http://localhost:9091/'


bacen:
  pix:
    url: 'http://localhost:8082/api'